version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - backend-network

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - backend-network
    depends_on:
      - product-db

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    networks:
      - backend-network
    depends_on:
      - user-db

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - backend-network
    depends_on:
      - order-db

  cart-service:
    build: ./cart-service
    ports:
      - "3004:3004"
    networks:
      - backend-network
    depends_on:
      - cart-db

  payment-service:
    build: ./payment-service
    ports:
      - "3005:3005"
    networks:
      - backend-network

  product-db:
    image: mongo
    volumes:
      - product-db:/data/db
    networks:
      - backend-network

  user-db:
    image: mongo
    volumes:
      - user-db:/data/db
    networks:
      - backend-network

  order-db:
    image: mongo
    volumes:
      - order-db:/data/db
    networks:
      - backend-network

  cart-db:
    image: mongo
    volumes:
      - cart-db:/data/db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  product-db:
  user-db:
  order-db:
  cart-db: